# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-taudor-github-io'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Posts', path: 'menu', url: 'posts.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/taudor'}
- {icon: 'twitter', link: 'https://twitter.com/t_soroceanu'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
